CREATE OR REPLACE FUNCTION NOMEDEP (PDEPTO IN NUMBER) RETURN VARCHAR2 IS
  -- DECLARAÇÃO DE VÁRIAVEIS
  VNOME   DEPT.DNAME%TYPE;
BEGIN
  SELECT DNAME INTO VNOME
  FROM DEPT
  WHERE DEPTNO = PDEPTO;
  RETURN VNOME;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        VNOME := 'DEPARTAMENTO INEXISTENTE';
        RETURN VNOME;
      WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001,SQLERRM(SQLCODE));
END;

SELECT NOMEDEP (1) FROM DUAL;
                                               
CREATE OR REPLACE FUNCTION FUNC_SAL(vCod IN NUMBER, vSAL IN NUMBER) 
RETURN NUMBER 
IS
vcCOD NUMBER;
vcSAL NUMBER;


SELECT * FROM SALGRADE;
SELECT * FROM EMP;
