-- CRIAR UMA FUNÇÃO QUE RECEBA COMO PARÂMETRO O CODIGO DO DEPARTAMENTO
-- E RETORNE O NOME DO MESMO. CASO NÃO SEJA ENCONTRADO, RETORNAR A MENSAGEM
-- DEPARTAMENTO INEXISTENTE

CREATE OR REPLACE FUNCTION NOMEDEP (PDEPTO IN NUMBER) RETURN VARCHAR2 IS
  -- DECLARAÇÃO DE VÁRIAVEIS
  VNOME   DEPT.DNAME%TYPE;
BEGIN
  SELECT DNAME INTO VNOME
  FROM DEPT
  WHERE DEPTNO = PDEPTO;
  RETURN VNOME;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        VNOME := 'DEPARTAMENTO INEXISTENTE';
        RETURN VNOME;
      WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001,SQLERRM(SQLCODE));
END;

SELECT NOMEDEP (1) FROM DUAL;

 
-- CRIAR UMA FUNÇÃO QUE RECEBA COMO PARÂMETRO O CODIGO DO FUNCIONARIO E O SALARIO
-- E RETORNE A GRADE SALARIAL QUE O MESMO SE ENCONTRA (SALGRADE)
-- CASO NÃO ENCONTRAE O FUNCIONARIO RETORNAR -1

CREATE OR REPLACE FUNCTION FUNC_SAL(vCod IN NUMBER, vSAL IN NUMBER) 
RETURN NUMBER 
IS
vcCOD NUMBER;
vcSAL NUMBER;


SELECT * FROM SALGRADE;
SELECT * FROM EMP;